### ISSUE TITLE
[System] Module for creating a single csv from an image dataset.

### ISSUE THREAD

**Issue by jjjimenez100** [jjjimenez100/A-Silent-Voice#9]
Resize the image into a considerable low pixel count and convert it to grayscale. Append the pixel's matrix to a single row in the csv file, including its label/class.

**Comment by jerichodiaz** [comment]
Review https://github.com/jjjimenez100/A-Silent-Voice/commit/7345d782e657261b89d38e4ca9b6dde645bd2439 pls

**Comment by jjjimenez100** [comment]
Should've closed the issue after referencing it out.
